parameters:
#    royopa_sicin.example.class: Royopa\SicinBundle\Example

services:
#    royopa_sicin.example:
#        class: %royopa_sicin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
